version: '3.1'

services:

  web:
    image: php:7.4-apache
    container_name: my-php-apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html

  db:
    image: mysql:8.0.19
    container_name: db
    restart: always
    environment:
      TZ: "Africa/Lagos"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "Kikelomo123@"
      MYSQL_USER: 'Kikelomo'
      MYSQL_PASSWORD: 'Kikelomo123@'
      MYSQL_DATABASE: 'kikedb'
      #TZ: "Africa/Lagos"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # mysql:
  #   image: mysql:5.7
  #   container_name: my-mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Kikelomo123@
  #     MYSQL_DATABASE: kikedb
  #     MYSQL_USER: Kikelomo
  #     MYSQL_PASSWORD: Kikelomo123@
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    restart: always
    # links:
    #   - mysql:db
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Kikelomo123@

  adminer:
    image: adminer
    restart: always
    ports:
      - 8182:8080

volumes:
  mysql-data: